/**
 * Server-side auto-publishing to the official MCP Registry.
 *
 * Every doc2mcp project that becomes "ready" can be published to
 * registry.modelcontextprotocol.io under the platform-owned namespace
 * `io.github.doc2mcp/<slug>`. Because the registry requires namespace
 * ownership (GitHub OAuth for `io.github.*`), this runs with a single
 * org-scoped GitHub token stored in `MCP_REGISTRY_GITHUB_TOKEN`. Without
 * that secret the publisher is a graceful no-op so local/dev and forks
 * keep working.
 *
 * Flow (see registry docs `/v0.1/auth/github-at` + `/v0.1/publish`):
 *   1. Exchange the GitHub access token for a short-lived registry JWT.
 *   2. POST the ServerJSON manifest to the publish endpoint.
 *
 * Versions auto-increment per docs: the patch component is derived from
 * the project's last-sync timestamp so every re-crawl publishes a fresh
 * registry version without manual bumps.
 */

import { getDoc2McpBaseUrl } from "@/lib/doc2mcp/app-url";
import { createLogger } from "@/lib/observability/logger";

const log = createLogger("mcp-registry");

const SERVER_SCHEMA =
  "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json";

const DEFAULT_REGISTRY_BASE = "https://registry.modelcontextprotocol.io";
const NAMESPACE = process.env.MCP_REGISTRY_NAMESPACE ?? "io.github.doc2mcp";
const SOURCE_REPO =
  process.env.MCP_REGISTRY_SOURCE_REPO ?? "https://github.com/doc2mcp/doc2mcp";

const MAX_DESCRIPTION = 100;
const TOKEN_TIMEOUT_MS = 8000;
const PUBLISH_TIMEOUT_MS = 12_000;

export type RegistryInfo = {
  name: string;
  version: string;
  url: string;
  status: "published" | "skipped" | "error";
  publishedAt: string;
  message?: string;
};

type PublishInput = {
  projectId: string;
  projectName?: string | null;
  sourceUrl?: string | null;
  /** ms epoch used to derive an auto-incrementing registry version. */
  versionSeed?: number;
};

function registryBase(): string {
  return (process.env.MCP_REGISTRY_BASE_URL ?? DEFAULT_REGISTRY_BASE).replace(
    /\/$/,
    ""
  );
}

/** Slug constrained to the registry name grammar `[a-zA-Z0-9._-]+`. */
export function registrySlug(
  name: string | null | undefined,
  id: string
): string {
  const fallback = `doc2mcp-${id.slice(0, 8)}`;
  if (!name) {
    return fallback;
  }
  const slug = name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^[-.]+|[-.]+$/g, "")
    .slice(0, 48);
  return slug || fallback;
}

export function registryServerName(
  name: string | null | undefined,
  id: string
): string {
  return `${NAMESPACE}/${registrySlug(name, id)}`;
}

/** Public, shareable listing URL for the marketplace to link out to. */
export function registryListingUrl(
  name: string | null | undefined,
  id: string
): string {
  const full = registryServerName(name, id);
  return `${DEFAULT_REGISTRY_BASE}/?search=${encodeURIComponent(full)}`;
}

function deriveVersion(seed: number | undefined): string {
  const ms = seed && Number.isFinite(seed) ? seed : Date.now();
  // Timestamp-based patch keeps every re-sync strictly increasing.
  return `1.0.${Math.floor(ms / 1000)}`;
}

function buildManifest(input: PublishInput, version: string) {
  const slug = registrySlug(input.projectName, input.projectId);
  const rawDescription = input.projectName
    ? `MCP server for ${input.projectName} documentation, generated by doc2mcp.`
    : "MCP server generated by doc2mcp from documentation.";
  const description =
    rawDescription.length > MAX_DESCRIPTION
      ? `${rawDescription.slice(0, MAX_DESCRIPTION - 1)}…`
      : rawDescription;

  return {
    $schema: SERVER_SCHEMA,
    name: `${NAMESPACE}/${slug}`,
    title: input.projectName ?? slug,
    description,
    version,
    repository: {
      url: SOURCE_REPO,
      source: "github",
    },
    remotes: [
      {
        type: "streamable-http",
        url: `${getDoc2McpBaseUrl()}/api/mcp/${input.projectId}/mcp`,
        headers: [
          {
            name: "Authorization",
            description:
              "Bearer <your project MCP token> from the project's Connect tab. Treat it like a password.",
            isRequired: true,
            isSecret: true,
          },
        ],
      },
    ],
  };
}

async function exchangeGithubToken(
  githubToken: string
): Promise<string | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TOKEN_TIMEOUT_MS);
  try {
    const res = await fetch(`${registryBase()}/v0.1/auth/github-at`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ github_token: githubToken }),
      signal: controller.signal,
    });
    if (!res.ok) {
      log.warn("auth.failed", { status: res.status });
      return null;
    }
    const data = (await res.json()) as {
      registry_token?: string;
      token?: string;
    };
    return data.registry_token ?? data.token ?? null;
  } catch (error) {
    log.error("auth.error", error);
    return null;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Best-effort publish. Never throws — the pipeline must not fail because
 * the external registry is unreachable or unconfigured.
 */
export async function publishProjectToRegistry(
  input: PublishInput
): Promise<RegistryInfo> {
  const version = deriveVersion(input.versionSeed);
  const name = registryServerName(input.projectName, input.projectId);
  const url = registryListingUrl(input.projectName, input.projectId);
  const base: Omit<RegistryInfo, "status" | "message"> = {
    name,
    version,
    url,
    publishedAt: new Date().toISOString(),
  };

  const githubToken = process.env.MCP_REGISTRY_GITHUB_TOKEN;
  if (!githubToken) {
    return {
      ...base,
      status: "skipped",
      message: "MCP_REGISTRY_GITHUB_TOKEN not configured",
    };
  }

  if (process.env.MCP_REGISTRY_AUTOPUBLISH === "false") {
    return { ...base, status: "skipped", message: "Auto-publish disabled" };
  }

  const registryToken = await exchangeGithubToken(githubToken);
  if (!registryToken) {
    return {
      ...base,
      status: "error",
      message: "Could not exchange GitHub token for a registry token",
    };
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), PUBLISH_TIMEOUT_MS);
  try {
    const res = await fetch(`${registryBase()}/v0.1/publish`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${registryToken}`,
      },
      body: JSON.stringify(buildManifest(input, version)),
      signal: controller.signal,
    });
    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      log.warn("publish.failed", {
        status: res.status,
        detail: detail.slice(0, 300),
      });
      return {
        ...base,
        status: "error",
        message: `Registry publish failed (${res.status})`,
      };
    }
    log.info("publish.ok", { name, version });
    return { ...base, status: "published" };
  } catch (error) {
    log.error("publish.error", error);
    return {
      ...base,
      status: "error",
      message: error instanceof Error ? error.message : "Publish error",
    };
  } finally {
    clearTimeout(timer);
  }
}
