import { z } from "zod";
import { auth } from "@/app/(auth)/auth";
import { generatePdfBuffer } from "@/lib/pdf/generate";
import { isSupabaseConfigured } from "@/lib/supabase/env";
import { uploadToSupabaseStorage } from "@/lib/supabase/storage";

const bodySchema = z.object({
  title: z.string().min(1).max(200),
  content: z.string().min(1).max(200_000),
  footer: z.string().max(200).optional(),
  /** When true, returns the PDF bytes inline instead of uploading. */
  inline: z.boolean().optional(),
});

function slugify(input: string): string {
  return (
    input
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "document"
  );
}

export async function POST(request: Request) {
  const session = await auth();
  if (!session?.user?.id) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (session.user.type === "guest") {
    return Response.json(
      { error: "Sign in to generate PDFs." },
      { status: 401 }
    );
  }

  let parsed: z.infer<typeof bodySchema>;
  try {
    parsed = bodySchema.parse(await request.json());
  } catch {
    return Response.json({ error: "Invalid request body" }, { status: 400 });
  }

  try {
    const bytes = await generatePdfBuffer({
      title: parsed.title,
      content: parsed.content,
      footer:
        parsed.footer ??
        `Generated by doc2mcp · ${new Date().toLocaleString()}`,
    });

    if (parsed.inline || !isSupabaseConfigured()) {
      return new Response(new Uint8Array(bytes), {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${slugify(parsed.title)}.pdf"`,
        },
      });
    }

    const storagePath = `${session.user.id}/pdf/${Date.now()}-${slugify(parsed.title)}.pdf`;
    const uploaded = await uploadToSupabaseStorage(
      storagePath,
      bytes.buffer as ArrayBuffer,
      "application/pdf"
    );

    return Response.json({
      url: uploaded.url,
      pathname: uploaded.pathname,
      contentType: "application/pdf",
      name: `${slugify(parsed.title)}.pdf`,
      size: bytes.byteLength,
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return Response.json(
      {
        error:
          error instanceof Error ? error.message : "Could not generate PDF.",
      },
      { status: 500 }
    );
  }
}
