import type { ApiEndpoint, CompressedTool } from "@/types/platform";

export function generateTypeScriptSdk(
  projectName: string,
  endpoints: ApiEndpoint[],
  tools: CompressedTool[]
): string {
  const className = projectName.replace(/[^a-zA-Z0-9]/g, "") || "ApiClient";

  const methods = tools
    .map((tool) => {
      const params = Object.keys(
        (tool.parameters.properties as Record<string, unknown>) ?? {}
      );
      const paramList = params.map((p) => `${p}?: unknown`).join(", ");
      return `  async ${tool.name}(${paramList}): Promise<unknown> {
    // ${tool.endpoints.join(", ")}
    return this.request("${tool.name}", { ${params.join(", ")} });
  }`;
    })
    .join("\n\n");

  const rawMethods = endpoints
    .slice(0, 20)
    .map((e) => {
      const fnName = `${e.method.toLowerCase()}${e.path.replace(/[^a-zA-Z0-9]/g, "_")}`;
      return `  async ${fnName}(options?: RequestOptions): Promise<unknown> {
    return this.rawRequest("${e.method}", "${e.path}", options);
  }`;
    })
    .join("\n\n");

  return `/**
 * ${className} SDK
 * Generated by UniAI Platform
 */
export type RequestOptions = {
  params?: Record<string, string>;
  body?: unknown;
  headers?: Record<string, string>;
};

export class ${className} {
  constructor(
    private readonly baseUrl: string,
    private readonly apiKey: string
  ) {}

  private async request(tool: string, data: Record<string, unknown>): Promise<unknown> {
    const response = await fetch(\`\${this.baseUrl}/tools/\${tool}\`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: \`Bearer \${this.apiKey}\`,
      },
      body: JSON.stringify(data),
    });
    if (!response.ok) throw new Error(\`API error: \${response.status}\`);
    return response.json();
  }

  private async rawRequest(method: string, path: string, options?: RequestOptions): Promise<unknown> {
    const response = await fetch(\`\${this.baseUrl}\${path}\`, {
      method,
      headers: {
        "Content-Type": "application/json",
        Authorization: \`Bearer \${this.apiKey}\`,
        ...options?.headers,
      },
      body: options?.body ? JSON.stringify(options.body) : undefined,
    });
    if (!response.ok) throw new Error(\`API error: \${response.status}\`);
    return response.json();
  }

${methods}

  // Raw endpoints
${rawMethods}
}
`;
}

export function generatePythonSdk(
  projectName: string,
  tools: CompressedTool[]
): string {
  const className = projectName.replace(/[^a-zA-Z0-9]/g, "") || "ApiClient";

  const methods = tools
    .map((tool) => {
      return `    def ${tool.name}(self, **kwargs) -> dict:
        """${tool.description}
        Endpoints: ${tool.endpoints.join(", ")}
        """
        return self._request("${tool.name}", kwargs)`;
    })
    .join("\n\n");

  return `"""
${className} SDK
Generated by UniAI Platform
"""
import httpx
from typing import Any


class ${className}:
    def __init__(self, base_url: str, api_key: str):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self._client = httpx.Client(
            headers={"Authorization": f"Bearer {api_key}"}
        )

    def _request(self, tool: str, data: dict[str, Any]) -> dict:
        response = self._client.post(
            f"{self.base_url}/tools/{tool}",
            json=data,
        )
        response.raise_for_status()
        return response.json()

${methods}

    def close(self):
        self._client.close()
`;
}
