/**
 * Per-project "Publish to the MCP Registry" panel.
 *
 * Realistic constraints: the official MCP Registry requires the publisher
 * to prove namespace ownership via GitHub OIDC (`io.github.<org>/*`) or a
 * DNS-verified custom domain. doc2mcp cannot publish under arbitrary
 * users' namespaces from a server-side action, so this panel ships the
 * user a ready-to-publish bundle they can:
 *   1. drop into a GitHub repo under their own org, or
 *   2. publish from their machine with the `mcp-publisher` CLI.
 *
 * Either path takes ~2 minutes and is fully theirs to own — no creds
 * leave the device. The doc2mcp gateway entry (`io.github.doc2mcp/doc2mcp`)
 * remains the canonical "verified by doc2mcp" record and is the default
 * way clients discover the platform.
 */

"use client";

import { BadgeCheck, Check, Copy, Download, ExternalLink } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

type Props = {
  projectId: string;
  projectName?: string | null;
  docsUrl?: string | null;
  className?: string;
};

const REGISTRY_SEARCH_URL =
  "https://registry.modelcontextprotocol.io/v0.1/servers?search=doc2mcp";

const REGISTRY_DOCS_URL =
  "https://modelcontextprotocol.io/registry/github-actions";

const PUBLISHER_INSTALL = `# macOS / Linux
OS=$(uname -s | tr 'A-Z' 'a-z')
ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
curl -sSL \\
  "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_\${OS}_\${ARCH}.tar.gz" \\
  | tar xz mcp-publisher
./mcp-publisher login github-oidc   # or: github-token / dns
./mcp-publisher publish`;

function sanitizeProjectSlug(name: string | null | undefined, id: string) {
  const fallback = `doc2mcp-${id.slice(0, 8)}`;
  if (!name) {
    return fallback;
  }
  const slug = name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return slug || fallback;
}

export function PublishToRegistryPanel({
  projectId,
  projectName,
  docsUrl,
  className,
}: Props) {
  const [copied, setCopied] = useState<string | null>(null);

  const slug = sanitizeProjectSlug(projectName, projectId);

  const serverJson = useMemo(() => {
    const description = projectName
      ? `MCP server for ${projectName} documentation, generated by doc2mcp.`
      : "MCP server generated by doc2mcp from documentation.";

    const trimmed =
      description.length > 100 ? `${description.slice(0, 97)}...` : description;

    const payload: Record<string, unknown> = {
      $schema:
        "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json",
      name: `io.github.<your-github-org>/${slug}`,
      title: projectName ?? slug,
      description: trimmed,
      version: "1.0.0",
      repository: {
        url: "https://github.com/<your-github-org>/<your-repo>",
        source: "github",
      },
      remotes: [
        {
          type: "streamable-http",
          url: `https://doc2mcp.site/api/mcp/${projectId}/mcp`,
          headers: [
            {
              name: "Authorization",
              description:
                "Bearer <your project MCP token> — generate one under the project's Connect tab. Treat the token like a password.",
              isRequired: true,
              isSecret: true,
            },
          ],
        },
      ],
    };

    if (docsUrl) {
      (payload.repository as Record<string, unknown>).docsUrl = docsUrl;
    }

    return JSON.stringify(payload, null, 2);
  }, [docsUrl, projectId, projectName, slug]);

  function copyText(value: string, label: string) {
    if (typeof navigator === "undefined" || !navigator.clipboard) {
      return;
    }
    navigator.clipboard
      .writeText(value)
      .then(() => {
        setCopied(label);
        toast.success(`${label} copied`);
        setTimeout(() => setCopied(null), 1500);
      })
      .catch(() => {
        toast.error("Could not copy — long-press to select instead.");
      });
  }

  function downloadServerJson() {
    if (typeof window === "undefined") {
      return;
    }
    const blob = new Blob([serverJson], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "server.json";
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <div
      className={cn(
        "relative overflow-hidden rounded-xl border border-violet-500/25 bg-gradient-to-br from-violet-500/8 via-card/40 to-fuchsia-500/8 p-5 backdrop-blur-xl",
        className
      )}
    >
      <div className="pointer-events-none absolute top-0 right-0 size-40 rounded-full bg-violet-500/15 blur-3xl" />
      <div className="relative space-y-4">
        <div className="flex items-start gap-3">
          <BadgeCheck
            aria-hidden="true"
            className="mt-0.5 size-5 text-violet-400"
          />
          <div className="min-w-0 space-y-2">
            <p className="font-medium text-violet-100 text-sm">
              Publish this MCP to the official Registry (optional)
            </p>
            <p className="text-muted-foreground text-sm">
              Make this server discoverable in the{" "}
              <a
                className="font-mono text-foreground underline underline-offset-2"
                href={REGISTRY_SEARCH_URL}
                rel="noreferrer noopener"
                target="_blank"
              >
                MCP Registry
              </a>{" "}
              so anyone using Cursor, Claude, or Windsurf can find it alongside
              your docs. We can&apos;t publish under your namespace for you (the
              registry requires{" "}
              <span className="text-foreground">GitHub OIDC</span> or{" "}
              <span className="text-foreground">DNS verification</span>), but
              the bundle below is ready to push in ~2 minutes.
            </p>
          </div>
        </div>

        <ol className="space-y-3 text-sm">
          <Step n={1} title="Grab the generated server.json">
            <p className="text-muted-foreground">
              Edit{" "}
              <code className="font-mono text-foreground">
                {"<your-github-org>"}
              </code>{" "}
              and{" "}
              <code className="font-mono text-foreground">{"<your-repo>"}</code>{" "}
              to point at a repo inside your GitHub organisation.
            </p>
            <pre className="mt-2 max-h-72 overflow-auto rounded-lg border border-border/50 bg-background/70 p-3 font-mono text-[11px] text-foreground/85 leading-relaxed">
              {serverJson}
            </pre>
            <div className="mt-2 flex flex-wrap gap-2">
              <Button
                onClick={() => copyText(serverJson, "server.json")}
                size="sm"
                type="button"
                variant="outline"
              >
                {copied === "server.json" ? (
                  <Check className="mr-1.5 size-3.5" />
                ) : (
                  <Copy className="mr-1.5 size-3.5" />
                )}
                Copy
              </Button>
              <Button
                onClick={downloadServerJson}
                size="sm"
                type="button"
                variant="outline"
              >
                <Download className="mr-1.5 size-3.5" />
                Download
              </Button>
            </div>
          </Step>

          <Step n={2} title="Publish from your machine (fastest)">
            <pre className="mt-2 overflow-auto rounded-lg border border-border/50 bg-background/70 p-3 font-mono text-[11px] text-foreground/85 leading-relaxed">
              {PUBLISHER_INSTALL}
            </pre>
            <Button
              className="mt-2"
              onClick={() => copyText(PUBLISHER_INSTALL, "Publisher commands")}
              size="sm"
              type="button"
              variant="outline"
            >
              {copied === "Publisher commands" ? (
                <Check className="mr-1.5 size-3.5" />
              ) : (
                <Copy className="mr-1.5 size-3.5" />
              )}
              Copy commands
            </Button>
          </Step>

          <Step n={3} title="Or wire a GitHub Action for hands-off releases">
            <p className="text-muted-foreground">
              Push{" "}
              <code className="font-mono text-foreground">server.json</code> and
              a small workflow file to a repo in your GitHub org. Every{" "}
              <code className="font-mono text-foreground">v*</code> tag will
              re-publish the entry. Full template:
            </p>
            <Button
              asChild
              className="mt-2"
              size="sm"
              type="button"
              variant="outline"
            >
              <a
                href={REGISTRY_DOCS_URL}
                rel="noreferrer noopener"
                target="_blank"
              >
                <ExternalLink aria-hidden="true" className="mr-1.5 size-3.5" />
                Registry GitHub Actions guide
              </a>
            </Button>
          </Step>
        </ol>

        <p className="rounded-lg border border-border/40 bg-background/30 px-3 py-2 text-[11px] text-muted-foreground">
          The bundle keeps your project token{" "}
          <span className="text-foreground">out</span> of the public registry —
          only the endpoint template lives there. Each AI client supplies its
          own Bearer when it connects. You can rotate the token any time from
          the Connect tab without re-publishing.
        </p>
      </div>
    </div>
  );
}

function Step({
  n,
  title,
  children,
}: {
  n: number;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <li className="flex gap-3">
      <span className="flex size-6 shrink-0 items-center justify-center rounded-lg border border-violet-500/40 bg-violet-500/15 font-mono text-[11px] text-violet-200">
        {n}
      </span>
      <div className="min-w-0 flex-1 space-y-1">
        <p className="font-display font-semibold text-foreground text-sm">
          {title}
        </p>
        <div className="text-muted-foreground text-sm leading-relaxed">
          {children}
        </div>
      </div>
    </li>
  );
}
