import "server-only";

import { tool } from "ai";
import { z } from "zod";
import { generatePdfBuffer } from "@/lib/pdf/generate";
import { isSupabaseConfigured } from "@/lib/supabase/env";
import { uploadToSupabaseStorage } from "@/lib/supabase/storage";

function slugify(input: string): string {
  return (
    input
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "document"
  );
}

/**
 * Builds a chat tool that lets the model render a clean PDF from markdown.
 *
 * The PDF is generated server-side with pdf-lib (no native deps) and, when
 * Supabase storage is configured, uploaded to the user's bucket. The tool
 * returns a public download URL the chat UI can render inline.
 *
 * Scoped to a user id so the storage path stays partitioned per user.
 */
export const generatePdfTool = ({ userId }: { userId: string }) =>
  tool({
    description: [
      "Generate a downloadable PDF document from markdown.",
      "Use this when the user explicitly asks for a PDF — e.g. report,",
      "invoice, summary, cheat sheet, certificate, study notes, or anything",
      "they want as a downloadable file.",
      "Pass a clear title and well-structured markdown (headings, lists,",
      "paragraphs, fenced code blocks). Returns a download URL.",
    ].join(" "),
    inputSchema: z.object({
      title: z
        .string()
        .min(1)
        .max(200)
        .describe("Document title — shown at the top of the PDF."),
      content: z
        .string()
        .min(1)
        .max(200_000)
        .describe(
          "Body in markdown. Supports # / ## / ### headings, paragraphs, " +
            "bullet/ordered lists, fenced code blocks, and --- horizontal rules."
        ),
      footer: z
        .string()
        .max(200)
        .optional()
        .describe(
          "Optional footer line shown on every page (e.g. author, date)."
        ),
    }),
    execute: async ({ title, content, footer }) => {
      try {
        const bytes = await generatePdfBuffer({
          title,
          content,
          footer:
            footer ?? `Generated by doc2mcp · ${new Date().toLocaleString()}`,
        });

        if (!isSupabaseConfigured()) {
          return {
            ok: false as const,
            error:
              "Supabase storage is not configured on this deployment, so the PDF cannot be hosted.",
          };
        }

        const filename = `${slugify(title)}.pdf`;
        const storagePath = `${userId}/pdf/${Date.now()}-${filename}`;
        const uploaded = await uploadToSupabaseStorage(
          storagePath,
          bytes.buffer as ArrayBuffer,
          "application/pdf"
        );

        return {
          ok: true as const,
          url: uploaded.url,
          name: filename,
          contentType: "application/pdf",
          size: bytes.byteLength,
          title,
        };
      } catch (error) {
        return {
          ok: false as const,
          error:
            error instanceof Error ? error.message : "PDF generation failed.",
        };
      }
    },
  });
